version: "3.8"

services:

    testing:
        image: danjoyce/dan_test
        ports:
            - 2000:1000
        environment:
        - USER=$USER
        - PASSWORD=12345

    testing_2:
        image: danjoyce/dan_test
        ports:
            - 100:1000
        env_file:
            - ./.env

    testing_3:
        image: danjoyce/dan_test
        ports:
            - 130:1000
        env_file:
            - ./second.env

    testing_4:
        image: danjoyce/dan_test
        ports:
            - 140:1000
        env_file:
            - ./second.env
        

