version: "3.8"

services:

    testing:
        image: dan_test
        ports:
            - 2000:1000
        environment:
            - USER=test
            - PASSWORD=12345

    testing_2:
        image: dan_test
        ports:
            - 100:1000
        env_file:
            - ./.env

    testing_3:
        image: dan_test
        ports:
            - 130:1000
        env_file:
            - ./second.env
        

