version: "3.8"

services:

    testing:
        image: danjoyce/dan_test
        ports:
            - 1010:1000
        environment:
        - USER=$USER
        - ATEST=$ATEST
        - PASSWORD=12345

    testing_2:
        image: danjoyce/dan_test
        ports:
            - 1020:1000
        env_file:
            - ./.env

    testing_3:
        image: danjoyce/dan_test
        ports:
            - 1030:1000
        env_file:
            - ./second.env

    testing_4:
        image: danjoyce/dan_test
        ports:
            - 1040:1000
        env_file:
            - USER=ExplicitlySet
            - ATEST=ExplicitTest
        

